### ISSUE TITLE
not able to install extension

### ISSUE THREAD

**Issue by Chandrak1907** [aquirdTurtle/Collapsible_Headings#13]
I get below error:

> (pyconnect_py27) [a115505@xhadrevrm7p ~]$ jupyter labextension install @aquirdturtle/collapsible_headings  --debug
Searching [u'/had/home/a115505', '/had/home/a115505/.jupyter', '/usr/platform/miniconda3/envs/pyconnect_py27/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /usr/platform/miniconda3/envs/pyconnect_py27/etc/jupyter
Looking for jupyter_config in /had/home/a115505/.jupyter
Looking for jupyter_config in /had/home/a115505
Traceback (most recent call last):
File "/usr/platform/miniconda3/envs/pyconnect_py27/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 79, in start
    ans = self.run_task()
File "/usr/platform/miniconda3/envs/pyconnect_py27/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 108, in run_task
    for arg in self.extra_args
File "/usr/platform/miniconda3/envs/pyconnect_py27/lib/python2.7/site-packages/jupyterlab/commands.py", line 227, in install_extension
    _node_check()
File "/usr/platform/miniconda3/envs/pyconnect_py27/lib/python2.7/site-packages/jupyterlab/commands.py", line 1466, in _node_check
    proc = Process(['node', 'node-version-check.js'], cwd=HERE, quiet=True) File "/usr/platform/miniconda3/envs/pyconnect_py27/lib/python2.7/site-packages/jupyterlab_launcher/process.py", line 109, in __init__
    kwargs['stdout'] = subprocess.DEVNULL
AttributeError: 'module' object has no attribute 'DEVNULL'
Errored, use --debug for full output:
AttributeError: 'module' object has no attribute 'DEVNULL'

**Comment by aquirdTurtle** [comment]
I'm suspicious this might be because it looks like you're using python 2.7 - I never did any tests with python 2. Do you have a python 3 environment you can test this in easily?

**Comment by Chandrak1907** [comment]
yes.. I was using python 2.7.
